config/routes.rb
Rails.application.routes.draw do

  post 'battles/get_finished'

  get 'battles/lose'

  get 'battles/finished'

  post 'battles/skill_update/:id' => 'battles#skill_update', as: 'battles_skill_update'

  get 'battles/show/:my_id/:opponent_id' => 'battles#show', as: 'battles_show'

  resources :skill_data

<<<<<<< HEAD
  get 'users/monster_show/:id' => 'users#monster_show', as: 'users_monster_show'
=======
  get 'users/request_approval/:monster_id/:user_id' => 'users#request_approval', as: 'users_request_approval'

  delete 'users/request_rejection/:monster_id/:user_id' => 'users#request_rejection', as: 'users_request_rejection'

  post 'users/exchange/:id' => 'users#exchange', as: 'users_exchange'
>>>>>>> 7dc2a63a1595bd43b453c1cac8de534c0312d530

  post 'users/monster_having/:id' => 'users#monster_having', as: 'users_monster_having'

  post 'users/monster_first/:id' => 'users#monster_first', as: 'users_monster_first'

  post 'users/monster_have/:id' => 'users#monster_have', as: 'users_monster_have'

  delete 'users/monster_destroy/:id' => 'users#monster_destroy', as: 'users_monster_destroy'

  get 'users/loginform'

  post 'users/login'

  post 'users/logout'

  get 'users/mypage'

  get 'users/practice'

  get 'users/boss'

  get 'users/communication'

  get 'users/settings'

  get '/' => 'homes#top'

  post 'monster_detail/synchronize'

  post 'monster_detail/recovery'

  resources :users do
    member do
      resources :monster_detail
    end
  end
  resources :monster_data
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, {presence: true, length: { maximum: 5 }}
  validates :email, {presence: true, uniqueness: true}
  validates :password, presence: true

  has_many :monster_detail
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, {only: [:show, :logout, :mypage, :practice, :boss, :communication, :settings]}
  before_action :level_judge, only: :mypage

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.ball_num = 5
    @user.level = 1
    @user.exp = 0
    @user.gold = 2000
    @user.last_login_at = Time.now
    @user.last_event_at = Date.today - 1
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to(users_mypage_path)
    else
      render(new_user_path)
    end
  end

  def show
  end

  def update
    if params[:user][:ball_num]
      @current_user.ball_num += params[:user][:ball_num].to_i
      @current_user.gold -= params[:user][:ball_num].to_i * 100
      @current_user.save
    end
  end

  def loginform
  end

  def login
    @user = User.find_by(email: params[:user][:email])
    if @user
      if @user.password == params[:user][:password]
        session[:user_id] = @user.id
        @user.last_login_at = Time.now
        @user.save
        flash[:notice] = "ログインしました"
        redirect_to(users_mypage_path)
      else
        @error_message = "メールアドレスまたはパスワードが間違っています"
        @email = params[:user][:email]
        @password = params[:user][:password]
        render(users_loginform_path)
      end
    else
      @error_message = "メールアドレスまたはパスワードが間違っています"
      @email = params[:user][:email]
      @password = params[:user][:password]
      render(users_loginform_path)
    end
  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end

  def monster_show
    @monster = MonsterDetail.find(params[:id].to_i)
    if @monster.level > 1
      @before_level_exp_sum = level_up_exp_array[@monster.level-2].to_i
    else
      @before_level_exp_sum = 0
    end
    @next_level_exp = exp_by_one_array[@monster.level-1].to_i
  end

  def monster_having
    new_having_monster = MonsterDetail.find(params[:id].to_i)
    if MonsterDetail.where(user_id: @current_user.id, having_flag: 1).count >= 6
      flash[:notice] = '手持ちモンスターは6匹までです。'
    else
      new_having_monster.having_flag = 1
      new_having_monster.save
    end
    @monster = MonsterDetail.where(user_id: @current_user.id, have_flag: 1).order("having_flag DESC").order("updated_at DESC")
  end

  def monster_first
    first_monster = MonsterDetail.find(params[:id].to_i)
    first_monster.update(updated_at: Time.now)
    @monster = MonsterDetail.where(user_id: @current_user.id, have_flag: 1).order("having_flag DESC").order("updated_at DESC")
  end

  def monster_have
    new_have_monster = MonsterDetail.find(params[:id].to_i)
    if MonsterDetail.where(user_id: @current_user.id, having_flag: 1).count <= 1
      flash[:notice] = '手持ちモンスターは1匹以上必要です。'
    else
      new_have_monster.having_flag = 0
      new_have_monster.save
    end
    @monster = MonsterDetail.where(user_id: @current_user.id, have_flag: 1).order("having_flag DESC").order("updated_at DESC")
  end

  def monster_destroy
    destroyed_monster = MonsterDetail.find(params[:id].to_i)
    if MonsterDetail.where(user_id: @current_user.id, having_flag: 1).count <= 1 && destroyed_monster.having_flag == 1
      flash[:notice] = '手持ちモンスターは1匹以上必要です。'
    else
      destroyed_monster.having_flag = 0
      destroyed_monster.have_flag = 0
      destroyed_monster.save
    end
    @monster = MonsterDetail.where(user_id: @current_user.id, have_flag: 1).order("having_flag DESC").order("updated_at DESC")
  end

  def mypage
    # ずかん
    @zukan = MonsterDatum.all
    @monster = MonsterDetail.where(user_id: @current_user.id, have_flag: 1).order("having_flag DESC").order("updated_at DESC")
    if @current_user.level > 1
      @before_level_exp_sum = level_up_exp_array[@current_user.level-2].to_i
    else
      @before_level_exp_sum = 0
    end
    @next_level_exp = exp_by_one_array[@current_user.level-1].to_i
    @how_many_monsters = MonsterDetail.where(user_id: @current_user.id, had_flag: 1).pluck(:monster_datum_id).uniq.count
  end

  def practice
    @my_first_monster = @current_user.monster_detail.where(having_flag: 1).order("updated_at DESC").reject {|monster| monster.hp_left == 0 }.first
    @take_3_monsters_at_random_level_adjusted = []
    MonsterDatum.order("RANDOM()").limit(3).each do |monster|
      if @current_user.level-3 > 1
        monster.level = rand(@current_user.level-3..@current_user.level+3)
      else
        monster.level = rand(1..@current_user.level+3)
      end
      monster.hp += monster.hp_add*(monster.level-1)
      monster.attack += monster.attack_add*(monster.level-1)
      monster.defence += monster.defence_add*(monster.level-1)
      monster.speed += monster.speed_add*(monster.level-1)
      if monster.level > 1
        monster.exp = level_up_exp_array[monster.level-2].to_i
      else
        monster.exp = 0
      end
      monster = MonsterDetail.create(
        name: "#{monster.name}",
        hp_left: monster.hp,
        hp: monster.hp,
        attack: monster.attack,
        defence: monster.defence,
        speed: monster.speed,
        hp_add: monster.hp_add,
        attack_add: monster.attack_add,
        defence_add: monster.defence_add,
        speed_add: monster.speed_add,
        level: monster.level,
        exp: monster.exp,
        type: "#{monster.type}",
        user_id: 4,
        monster_datum_id: monster.id,
        having_flag: 0,
        have_flag: 0,
        had_flag: 0,
        seen_flag: 0)

      SkillDatum.order("RANDOM()").limit(3).each do |skill_data|
        SkillDetail.create(monster_detail_id: monster.id, skill_datum_id: skill_data.id, pp_left: skill_data.pp)
      end

      @take_3_monsters_at_random_level_adjusted << monster
    end

    if @current_user.last_login_at > Date.today.beginning_of_day && @current_user.last_event_at < Date.today.beginning_of_day
      @eventmonster = MonsterDatum.order("RANDOM()").limit(1)[0]
      @eventmonster.level = @current_user.level + 10
      @eventmonster.hp += @eventmonster.hp_add*(@eventmonster.level-1)
      @eventmonster.attack += @eventmonster.attack_add*(@eventmonster.level-1)
      @eventmonster.defence += @eventmonster.defence_add*(@eventmonster.level-1)
      @eventmonster.speed += @eventmonster.speed_add*(@eventmonster.level-1)
      @eventmonster.exp = level_up_exp_array[@eventmonster.level-2].to_i
      @eventmonster = MonsterDetail.create(
        name: "#{@eventmonster.name}",
        hp_left: @eventmonster.hp,
        hp: @eventmonster.hp,
        attack: @eventmonster.attack,
        defence: @eventmonster.defence,
        speed: @eventmonster.speed,
        hp_add: @eventmonster.hp_add,
        attack_add: @eventmonster.attack_add,
        defence_add: @eventmonster.defence_add,
        speed_add: @eventmonster.speed_add,
        level: @eventmonster.level,
        exp: @eventmonster.exp,
        type: "#{@eventmonster.type}",
        user_id: 4,
        monster_datum_id: @eventmonster.id,
        having_flag: 0,
        have_flag: 0,
        had_flag: 0,
        seen_flag: 0)

      SkillDatum.order("RANDOM()").limit(3).each do |skill_data|
        SkillDetail.create(monster_detail_id: @eventmonster.id, skill_datum_id: skill_data.id, pp_left: skill_data.pp)
      end
    end
  end

  def boss
  end

  def communication
    @user = User.new
    if params[:user]
      if params[:user][:id].to_i == @current_user.id
        flash[:notice] = "自分以外のトレーナーを選択してください。"
      else
        @searched_user = User.find(params[:user][:id].to_i)
      end
    end
    @requested_monster = MonsterDetail.where(user_id: @current_user.id, have_flag: 1).reject{|monster| monster.exchange == nil}
  end

  def exchange
    monster = MonsterDetail.find(params[:id].to_i)
    if monster.exchange == nil
      monster.exchange = "#{@current_user.id}"
    elsif monster.exchange.include?("#{@current_user.id}")
    else
      monster.exchange += "#{@current_user.id}"
    end
    monster.save
    flash[:notice] = "#{User.find(monster.user_id).name}さんにリクエストが送られました。"
    redirect_to(users_communication_path)
  end

  def request_approval
    @requested_monster = MonsterDetail.find(params[:monster_id].to_i)
    @request_user = User.find(params[:user_id].to_i)
    @request_user_monsters = MonsterDetail.where(user_id: @request_user, have_flag: 1)
  end

  def request_rejection
    requested_monster = MonsterDetail.find(params[:monster_id].to_i)
    request_user = User.find(params[:user_id].to_i)
    requested_monster.exchange.delete!("#{request_user.id}")
    requested_monster.save
    flash[:notice] = "#{request_user.name}さんからの#{requested_monster.name}へのリクエストを拒否しました。"
    @requested_monster = MonsterDetail.where(user_id: @current_user.id, have_flag: 1).reject{|monster| monster.exchange == nil}
  end

  def settings
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :image_name, :password)
  end

  def exp_by_one_array
    n = 25
    array = [25]
    for i in 1..1000 do
      n *= 1.1
      array << n
    end
    return array
  end

  def level_up_exp_array
    exp_array = []
    for j in 0..1000 do
      exp_array << exp_by_one_array[0..j].sum
    end
    return exp_array
  end

  def level_judge
    while @current_user.exp > level_up_exp_array[@current_user.level-1] do
      @current_user.level += 1
      flash[:notice] = "#{@current_user.name}のトレーナーレベルがLv.#{@current_user.level}に上がった！"
    end
    @current_user.save
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_koukan.html.erb
<%= form_for(@user, :url => {:controller => :users, :action => :communication}, method: :get, data: { remote: true }) do |f| %>
  <div class="form-group">
      <label>交換したい相手のトレーナーIDを入力してください</label>
      <%= f.number_field :id, id: "id-field", class: "form-control", value: 1, min: 1, max: User.all.count, style: "width: 300px; margin: auto;" %>
  </div>
  <%= f.submit "検索", class: "btn btn-default", style: "margin-bottom: 20px;" %>
<% end %>

<% if @searched_user %>
  <h3><%= @searched_user.name %>さんの手持ちモンスター</h3>
  <% @searched_user.monster_detail.each do |monster| %>
    <% if monster.have_flag == 1 %>
      <%= link_to(users_exchange_path(monster.id), method: :post, data: {confirm: "#{@searched_user.name}さんの#{monster.name}に対して交換リクエストを申請しますか？"}) do %>
        <div class="posts-index-item">
          <div class="monster-ball-icon-for-monster">
            <% unless monster.monster_datum.monster_detail.where(user_id: @current_user.id, had_flag: 1).empty? %>
              <%= image_tag('standard_ball.png') %>
            <% else %>
              <p>  </p>
            <% end %>
          </div>
          <div class="monster-detail-right">
            <div class="level-name" style="width: 80%;">
              <div class="monster-detail-level">
                Lv.<%= monster.level %>
              </div>
              <div class="monster-detail-name">
                <%= monster.name %>
              </div>
            </div>
            <div class="monster-detail-hp" style="width: 80%; margin-top: 10px;">
              <div class="progress">
                <% hp_ratio = (monster.hp_left/monster.hp.to_f)*100 %>
                <div class="progress-bar <%= "progress-bar-warning" if hp_ratio >= 25 && hp_ratio < 50 %> <%= "progress-bar-danger" if hp_ratio < 25 %>" role="progressbar" style="width: <%= hp_ratio %>%;">
                </div>
              </div>
              <p>HP: <%= monster.hp_left %>/<%= monster.hp %></p>
            </div>
          </div>
          <div class="post-left-for-monster">
            <%= image_tag(monster.monster_datum.image_name) %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<script type="text/javascript">
  $('.posts-index-item').css('background', '#FFFFFF');
  $('.posts-index-item').hover(function(){
    $(this).css('background', '#F5F5F5');
  }, function(){
    $(this).css('background', '');
  });
</script>

app/views/users/_kusamura.html.erb
<% @take_3_monsters_at_random_level_adjusted.each do |monster_data| %>
  <%= link_to(battles_show_path(@my_first_monster.id, monster_data.id), :data => {:confirm => "#{monster_data.name}とバトルしますか？"}) do %>
    <div class="posts-index-item">
      <div class="monster-ball-icon-for-monster">
        <% if MonsterDetail.where(user_id: @current_user.id, monster_datum_id: monster_data.monster_datum.id).pluck(:had_flag).max == 1 %>
          <%= image_tag('standard_ball.png') %>
        <% else %>
          <p>  </p>
        <% end %>
      </div>
      <div class="monster-detail-right">
        <div class="level-name" style="width: 80%;">
          <div class="monster-detail-level">
            Lv.<%= monster_data.level %>
          </div>
          <div class="monster-detail-name">
            <%= monster_data.name %>
          </div>
        </div>
        <div class="monster-detail-hp" style="width: 80%; margin-top: 10px;">
          <div class="progress">
          	<div class="progress-bar" role="progressbar" style="width: 100%;">
          	</div>
          </div>
          <p>HP: <%= monster_data.hp %>/<%= monster_data.hp %></p>
        </div>
      </div>
      <div class="post-left-for-monster">
        <%= image_tag(monster_data.monster_datum.image_name) %>
      </div>
    </div>
  <% end %>
<% end %>



<script type="text/javascript">
  $('.posts-index-item').css('background', '#FFFFFF');
  $('.posts-index-item').hover(function(){
    $(this).css('background', '#F5F5F5');
  }, function(){
    $(this).css('background', '');
  });
</script>

app/views/users/_monster.html.erb
<% @monster.each do |monster_data| %>
  <%= link_to(users_monster_show_path(monster_data.id)) do %>
    <div class="posts-index-item">
      <div class="monster-ball-icon-for-monster">
        <% if monster_data.having_flag == 1 %>
          <%= image_tag('standard_ball.png') %>
        <% else %>
          <p>  </p>
        <% end %>
      </div>
      <div class="monster-detail-right">
        <div class="level-name" style="width: 80%;">
          <div class="monster-detail-level">
            Lv.<%= monster_data.level %>
          </div>
          <div class="monster-detail-name">
            <%= monster_data.name %>
          </div>
        </div>
        <div class="monster-detail-hp" style="width: 80%; margin-top: 10px;">
          <div class="progress">
            <% hp_ratio = (monster_data.hp_left/monster_data.hp.to_f)*100 %>
          	<div class="progress-bar <%= "progress-bar-warning" if hp_ratio >= 25 && hp_ratio < 50 %> <%= "progress-bar-danger" if hp_ratio < 25 %>" role="progressbar" style="width: <%= hp_ratio %>%;">
          	</div>
          </div>
          <p>HP: <%= monster_data.hp_left %>/<%= monster_data.hp %></p>
        </div>
      </div>
      <div class="post-left-for-monster">
        <%= image_tag(monster_data.monster_datum.image_name) %>
      </div>
      <div class="monster-change-btn">
        <%= link_to '手持ち', users_monster_having_path(monster_data.id), method: :post, remote: true, class: 'btn btn-primary btn-xs monster-delete-btn' %>
        <%= link_to '先頭', users_monster_first_path(monster_data.id), method: :post, remote: true, class: 'btn btn-success btn-xs monster-delete-btn' %>
        <%= link_to '外す', users_monster_have_path(monster_data.id), method: :post, remote: true, class: 'btn btn-warning btn-xs monster-delete-btn' %>
        <%= link_to '捨てる', users_monster_destroy_path(monster_data.id), method: :delete, remote: true, data: {confirm: "#{monster_data.name}とお別れしますか？"}, class: 'btn btn-danger btn-xs monster-delete-btn' %>
      </div>
    </div>
  <% end %>
<% end %>



<script type="text/javascript">
  $('.posts-index-item').css('background', '#FFFFFF');
  $('.posts-index-item').hover(function(){
    $(this).css('background', '#F5F5F5');
  }, function(){
    $(this).css('background', '');
  });
</script>

app/views/users/_rucksack.html.erb

<h3><%= @current_user.name %>さんの所持金 : <%= @current_user.gold %>G</h3>
<div class="posts-index-item">
  <div class="monster-ball-icon-for-ruck">
    <%= image_tag('standard_ball.png') %>
  </div>
  <div class="ruck-left">
    <p>スタンダードボール × <%= @current_user.ball_num %></p>
    <br>
    <p>100G</p>
  </div>
  <div class="ruck-right">
    <% @user = @current_user %>
    <%= form_for(@user, data: { remote: true }) do |f| %>
      <div class="form-group">
          <label>いくつ購入しますか?</label>
          <%= f.number_field :ball_num, id: "ball-number-field", class: "form-control", value: 1, min: 1, max: @current_user.gold/100, style: "width: 120px; margin: auto;" %>
      </div>
      <%= f.submit "購入", class: "btn btn-default", style: "width: 50px;" %>
    <% end %>
  </div>
</div>

app/views/users/_userdetails.html.erb
<div class="user-details-name">
  <h3><%= @current_user.name %></h3>
</div>
<div class="user-details-icon">
  <%= image_tag("#{@current_user.image_name}") %>
</div>
<div class="user-details-exp">
  <p>TOTAL EXP : <%= @current_user.exp %></p>
</div>
<div class="user-details-level">
  <h3>Lv.<%= @current_user.level %></h3>
</div>
<div class="monster-detail-hp" style="width: 80%; margin-top: 10px;">
  <div class="progress">
    <% exp_ratio = ((@current_user.exp - @before_level_exp_sum)/@next_level_exp.to_f)*100 %>
    <div class="progress-bar" role="progressbar" style="width: <%= exp_ratio %>%;">
    </div>
  </div>
  <p><%= @current_user.exp - @before_level_exp_sum %>/<%= @next_level_exp %> XP</p>
</div>
<div class="user-details-gold">
  <%= image_tag('gold.png') %>
  <p><%= @current_user.gold %>G</p>
</div>
<div class="user-details-how-many-monsters">
  <%= image_tag('standard_ball.png') %>
  <p><%= @how_many_monsters %>匹</p>
</div>

app/views/users/communication.html.erb
<div class="main">
  <div class="centering">
    <!-- タブ・メニュー -->
    <ul class="nav nav-tabs">
    	<li class="active"><a href="#sampleContentA" data-toggle="tab">交換</a></li>
    	<li><a href="#sampleContentB" data-toggle="tab">対戦</a></li>
      <li><a href="#sampleContentC" data-toggle="tab">リクエスト</a></li>
    </ul>

    <!-- タブ内容 -->
    <div class="tab-content">
    	<div class="tab-pane active" id="sampleContentA">
        <div id="koukan">
          <%= render 'koukan' %>
        </div>
    	</div>
    	<div class="tab-pane" id="sampleContentB">
    		<%= render 'taisen' %>
    	</div>
      <div class="tab-pane" id="sampleContentC">
        <div id="request">
          <%= render 'request' %>
        </div>
    	</div>
    </div>
  </div>
</div>

app/views/users/loginform.html.erb
<div class="main">
  <div class="user-form-box">
    <h2>Log In</h2>
    <%= form_for :user, :url => {:action => 'login'} do |f| %>

      <% if @error_message %>
        <div id="error_explanation" class="alert alert-danger">
          <p><%= @error_message %></p>
        </div>
      <% end %>

      <div class="form-group">
          <label>email</label>
          <%= f.email_field :email, class: "form-control", value: @email %>
      </div>
      <div class="form-group">
          <label>password</label>
          <%= f.password_field :password, class: "form-control", value: @password %>
      </div>
      <%= f.submit "Log In", class: "btn btn-default btn-block", style: "width: 160px; margin-bottom: 30px;" %>
    <% end %>

  </div>

  <%= link_to 'Sign Up', new_user_path, class: "btn btn-default btn-block2 btn-change-form", style: "display: block;"%>

</div>

app/views/users/monster_destroy.js.erb
$('#monster').html('<%= escape_javascript(render("users/monster")) %>');
$('#flash').html('<%= escape_javascript(render("flash")) %>');
<% flash[:notice] = nil %>

app/views/users/monster_have.js.erb
$('#monster').html('<%= escape_javascript(render("users/monster")) %>');
$('#flash').html('<%= escape_javascript(render("flash")) %>');
<% flash[:notice] = nil %>

app/views/users/monster_having.js.erb
$('#monster').html('<%= escape_javascript(render("users/monster")) %>');
$('#flash').html('<%= escape_javascript(render("flash")) %>');
<% flash[:notice] = nil %>

app/views/users/mypage.html.erb
<div class="main">
  <div class="centering">
    <!-- タブ・メニュー -->
    <ul class="nav nav-tabs">
    	<li class="active"><a href="#sampleContentA" data-toggle="tab">ずかん</a></li>
    	<li><a href="#sampleContentB" data-toggle="tab">モンスター</a></li>
    	<li><a href="#sampleContentC" data-toggle="tab">リュック</a></li>
    	<li><a href="#sampleContentD" data-toggle="tab">かいふく</a></li>
      <li><a href="#sampleContentE" data-toggle="tab"><%= @current_user.name %></a></li>
    </ul>

    <!-- タブ内容 -->
    <div class="tab-content">
    	<div class="tab-pane active" id="sampleContentA">
        <%= render 'zukan' %>
    	</div>
    	<div class="tab-pane" id="sampleContentB">
        <div id='monster'>
          <%= render 'monster' %>
        </div>
    	</div>
    	<div class="tab-pane" id="sampleContentC">
        <div id='rucksack'>
          <%= render 'rucksack' %>
        </div>
    	</div>
    	<div class="tab-pane" id="sampleContentD">
    		<%= render 'recovery' %>
    	</div>
      <div class="tab-pane" id="sampleContentE">
        <%= render 'userdetails' %>
    	</div>
    </div>
  </div>
</div>

app/views/users/request_rejection.js.erb
$('#request').html('<%= escape_javascript(render("users/request")) %>');
$('#flash').html('<%= escape_javascript(render("flash")) %>');
<% flash[:notice] = nil %>

app/views/users/settings.html.erb
<div class="main">
  <div class="centering">
    <%= link_to 'Log Out', users_logout_path, class: "btn btn-default", method: :post %>
  </div>
</div>

app/views/users/show.html.erb
showだよ