config/routes.rb
Rails.application.routes.draw do

  post 'battles/get_finished'

  get 'battles/lose'

  get 'battles/finished'

  post 'battles/skill_update/:id' => 'battles#skill_update', as: 'battles_skill_update'

  get 'battles/show/:my_id/:opponent_id' => 'battles#show', as: 'battles_show'

  resources :skill_data

<<<<<<< HEAD
  get 'users/monster_show/:id' => 'users#monster_show', as: 'users_monster_show'
=======
  get 'users/request_approval/:monster_id/:user_id' => 'users#request_approval', as: 'users_request_approval'

  delete 'users/request_rejection/:monster_id/:user_id' => 'users#request_rejection', as: 'users_request_rejection'

  post 'users/exchange/:id' => 'users#exchange', as: 'users_exchange'
>>>>>>> 7dc2a63a1595bd43b453c1cac8de534c0312d530

  post 'users/monster_having/:id' => 'users#monster_having', as: 'users_monster_having'

  post 'users/monster_first/:id' => 'users#monster_first', as: 'users_monster_first'

  post 'users/monster_have/:id' => 'users#monster_have', as: 'users_monster_have'

  delete 'users/monster_destroy/:id' => 'users#monster_destroy', as: 'users_monster_destroy'

  get 'users/loginform'

  post 'users/login'

  post 'users/logout'

  get 'users/mypage'

  get 'users/practice'

  get 'users/boss'

  get 'users/communication'

  get 'users/settings'

  get '/' => 'homes#top'

  post 'monster_detail/synchronize'

  post 'monster_detail/recovery'

  resources :users do
    member do
      resources :monster_detail
    end
  end
  resources :monster_data
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  prepend_before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to(users_loginform_path)
    end
  end

  def forbid_login_user
    if @current_user
      flash[:notice] = "すでにログインしています"
      redirect_to(users_mypage_path)
    end
  end

  def super_user
    if @current_user.id != 1
      flash[:notice] = "あなたはこのページを閲覧することは出来ません"
      redirect_to(users_mypage_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flash.html.erb
<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/application/_header.html.erb
<nav class="navbar navbar-inverse">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<% if params[:controller] == "battles" %>
				<%= link_to 'War & Peace', '', class: "navbar-brand" %>
			<% elsif @current_user %>
				<%= link_to 'War & Peace', users_mypage_path, class: "navbar-brand" %>
			<% else %>
				<%= link_to 'War & Peace', '/', class: "navbar-brand" %>
			<% end %>
		</div>

		<div class="collapse navbar-collapse" id="navbarEexample7">
			<ul class="nav navbar-nav">
				<% if params[:action] == "top" %>
          <li><%= link_to 'Sign Up', new_user_path %></li>
          <li><%= link_to 'Log In', users_loginform_path %></li>
				<% elsif params[:controller] == "users" && params[:action] == "new" %>
          <li class="active"><%= link_to 'Sign Up', new_user_path %></li>
          <li><%= link_to 'Log In', users_loginform_path %></li>
				<% elsif params[:action] == "loginform" || params[:action] == "login" %>
          <li><%= link_to 'Sign Up', new_user_path %></li>
          <li class="active"><%= link_to 'Log In', users_loginform_path %></li>
        <% elsif params[:action] == "mypage" %>
          <li class="active"><%= link_to 'Mypage', users_mypage_path %></li>
          <li><%= link_to 'Practice', users_practice_path %></li>
          <li><%= link_to 'Boss', users_boss_path %></li>
          <li><%= link_to 'Communication', users_communication_path %></li>
          <li><%= link_to 'Settings', users_settings_path %></li>
        <% elsif params[:action] == "practice" %>
          <li><%= link_to 'Mypage', users_mypage_path %></li>
          <li class="active"><%= link_to 'Practice', users_practice_path %></li>
          <li><%= link_to 'Boss', users_boss_path %></li>
          <li><%= link_to 'Communication', users_communication_path %></li>
          <li><%= link_to 'Settings', users_settings_path %></li>
        <% elsif params[:action] == "boss" %>
          <li><%= link_to 'Mypage', users_mypage_path %></li>
          <li><%= link_to 'Practice', users_practice_path %></li>
          <li class="active"><%= link_to 'Boss', users_boss_path %></li>
          <li><%= link_to 'Communication', users_communication_path %></li>
          <li><%= link_to 'Settings', users_settings_path %></li>
        <% elsif params[:action] == "communication" %>
          <li><%= link_to 'Mypage', users_mypage_path %></li>
          <li><%= link_to 'Practice', users_practice_path %></li>
          <li><%= link_to 'Boss', users_boss_path %></li>
          <li class="active"><%= link_to 'Communication', users_communication_path %></li>
          <li><%= link_to 'Settings', users_settings_path %></li>
        <% elsif params[:action] == "settings" %>
          <li><%= link_to 'Mypage', users_mypage_path %></li>
          <li><%= link_to 'Practice', users_practice_path %></li>
          <li><%= link_to 'Boss', users_boss_path %></li>
          <li><%= link_to 'Communication', users_communication_path %></li>
          <li class="active"><%= link_to 'Settings', users_settings_path %></li>
				<% elsif params[:controller] == "battles" %>
				<% elsif @current_user.id == 1 %>
          <li><%= link_to 'MonsterData', monster_data_path %></li>
					<li><%= link_to 'SkillData', skill_data_path %></li>
					<li><%= link_to 'MonsterSynchronize', monster_detail_synchronize_path, method: :post %></li>
        <% else %>
          <li><%= link_to 'Mypage', users_mypage_path %></li>
          <li><%= link_to 'Practice', users_practice_path %></li>
          <li><%= link_to 'Boss', users_boss_path %></li>
          <li><%= link_to 'Communication', users_communication_path %></li>
          <li><%= link_to 'Settings', users_settings_path %></li>
        <% end %>
			</ul>
		</div>
	</div>
</nav>